# Generated by Django 3.1.3 on 2021-06-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
